In [1]:
"""
## What is an 'array'?
>> In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. 


==>Most Numpy array have some restriction. For instance:
* All elements of the array must be of the same type of data.
* Once created, the total size of the array can't be changed.
* The shape must be "rectangular", not "jagged"; eg: each row of two-dimensional array must have the same number of columns.
"""

import numpy as np

In [2]:
"""
One way to initialize an array is using a python sequence, such as a list. For example:
"""

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
print(a)

[1 2 3 4 5 6]


In [4]:
a[0]

1

In [5]:
# Array is mutable
a[0] = 10

In [6]:
print(a)

[10  2  3  4  5  6]


In [8]:
# Like list we can use Python slice notation for indexing.
print(a[:3])

[10  2  3]


In [9]:
"""
Note: One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.
"""

b = a[3:]
print(b)

[4 5 6]


In [10]:
print("Before:", a)
b[0] = 40
print("After:", a)

Before: [10  2  3  4  5  6]
After: [10  2  3 40  5  6]


In [11]:
"""
## Multi-dimensional Array:

Two- and higher-dimensional array can be initialize from nasted Python sequence
"""
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
"""
Another difference between an array and a list of lists is that an element of the array can be accessed by the index along each axis within a single set of square brackets, separated by commas. For instance, the element "8" is in row 1 and column 3:
"""
a[1, 3]

8

In [14]:
"""
Note: it is familiar practice in mathematics to prefer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second last. This generalize to arrays with any numbers of dimensions. 


Note: 
You might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, a 1-D (one-dimensional) array as a “vector”, a 2-D (two-dimensional) array as a “matrix”, or an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. For clarity, it is best to avoid the mathematical terms when referring to an array because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem that have these names (e.g. the fundamental data structure of PyTorch is the “tensor”).
"""

'\nNote: it is familiar practice in mathematics to prefer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second last. This generalize to arrays with any numbers of dimensions. \n\n\nNote: \nYou might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, a 1-D (one-dimensional) array as a “vector”, a 2-D (two-dimensional) array as a “matrix”, or an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. For clarity, it is best to avoid the mathematical terms when referring to an array because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem that have these names (e.g. the fundamental data structure

In [15]:
""" Array Attributes:
==> This section covers the 'ndim', 'shape', 'size', and 'dtype' attributes of an array.
"""

#1. ndim: return the number of dimension of the array
a.ndim



2

In [18]:
#2. shape: return tuple of non-negative integers that specify the number of elements along each dimension.
print(a.shape)

len(a.shape) == a.ndim

(3, 4)


True

In [21]:
#3. size: return total number of elements contained in array.
print(a.size)

import math

a.size == math.prod(a.shape)

12


True

In [22]:
#4. dtype: Arrays are typically "homogeneous" meaning that they
# contain elements of only one "data type".

a.dtype

dtype('int32')

In [28]:
"""
How to create a basic array
--> This section covers np.zeros(), np.ones(), np.empty(), np.arrange(), np.linspace()
"""

#1. np.zeros(): Easily create an array filled with zeros.
print("1d array: ", np.zeros(3))
print("\n\n2d array: \n", np.zeros((2, 3)))

1d array:  [0. 0. 0.]


2d array: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#2. np.ones(): Easily create array filled with ones.

np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
#3. np.empty(): This method creates an array whose initial content is random and depends on the state of the memory. The reason to use empty() over zeros() is speed - just make sure that every element afterward!

np.empty((5, 4))

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  1.11610210e-311,
        -3.64430086e+279],
       [ 0.00000000e+000,  0.00000000e+000,  1.11608498e-311,
         1.75812418e-155],
       [ 0.00000000e+000,  0.00000000e+000,  1.11608363e-311,
        -1.67516515e+137],
       [ 6.95246181e-310,  4.28752839e-284,  1.11608486e-311,
        -1.59804644e+057]])

In [40]:
#4. np.arange(): You can create an array with a range of elements:
print(np.arange(9))

#And even an array that contain a range of evenly spaced intervals. To do this, you will specify the:
# np.arange(first_number, last_number, step_size)

print(np.arange(2, 9, 2))

[0 1 2 3 4 5 6 7 8]
[2 4 6 8]


In [43]:
#5. np.linspace(): You can also use linspace() method to create an array with values that are spaced linearly  in a specified interval:

print(np.linspace(2, 9, num=5))
print("\n\n")
print(np.linspace(0, 2, num=20))

[2.   3.75 5.5  7.25 9.  ]



[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]


In [45]:
#6. Specifying your data type:
# While the default data type is floating point(np.float64), you can explicitly specify which data type you want using dtype keyword

print(np.ones((2, 3), dtype=np.int64))
print('\n=============>>\n')
np.empty((3, 5), dtype=np.int64)

[[1 1 1]
 [1 1 1]]

=============>>


array([[              0,               0,               0,
                      0,               0],
       [              0,               0,               0,
                      0,               0],
       [              0,               0,               0,
                      0, 137839914269218]], dtype=int64)

In [46]:
"""
Adding, removing, and sorting elements
"""

#1. sort(): Sorting an element in array. You can specify the axis, kind, and order when you call the function.
# You can quickly sort the numbers in ascending order with:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [58]:
#in addition to sort, which return sorted copy of an array, you can use:
#argsort: which is an indirect sort along a specified axis,
#lexsort: which is and indirect stable sort on multiple keys,
#searchsorted: which will find elements in a sorted array
#partition: which is a partial sort.

arr = np.array([[8, 2, 7, 10], [12, 4, 1, 9], [3, 6, 5, 11]])
print(np.sort(arr))
print('\n\n')
print(np.argsort(arr))

[[ 2  7  8 10]
 [ 1  4  9 12]
 [ 3  5  6 11]]



[[1 2 0 3]
 [2 1 3 0]
 [0 2 1 3]]


In [63]:
# .concatenate(): You can concatenate arrays with this method.
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10])
np.concatenate((a, c, b))

array([ 1,  2,  3,  4,  9, 10,  5,  6,  7,  8])

In [65]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
#Remove Elements: in order to remove elements from an array, it's simple to use indexing to select the elements that you want to keep

a = np.array([11, 12, 13, 14, 15])
#now i want to remove 12:
a = a[[0, 1, 3, 4]]
print(a)

[11 12 14 15]


In [76]:
# .ndim, .shape, .size in ndarray

arr = np.array([
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ],
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]
])

print(arr)
print('===================>>>')
print("dimension:", arr.ndim)
print('====================>>')
print("size:", arr.size)
print('====================>>')
print("shape:", arr.shape)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]
===================>>>
dimension: 3
====================>>
size: 24
====================>>
shape: (3, 2, 4)


In [77]:
"""
Reshape Array (arr.reshape())
--> reshape() method is used to change shape or dimension of an array without changing the actual data it contains.
    It allows you to recognize the elements of the array into different arrangement of rows and columns.

Note: Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.
eg: array with 6 elements --> .reshape(3, 2) ---> 3x2 = 6
"""

a = np.arange(6)
print("a:", a)
reshaped_a = a.reshape(3, 2)
print("reshaped a by (3, 2):", reshaped_a)

a: [0 1 2 3 4 5]
reshaped a by (3, 2): [[0 1]
 [2 3]
 [4 5]]


In [83]:
b = np.array([[0, 1],
              [2, 3],
              [4, 5]])
print(b)
print("=============>>")
print(b.reshape(2, 3))
print('============>>>')
print(b.reshape(6))

[[0 1]
 [2 3]
 [4 5]]
=============>>
[[0 1 2]
 [3 4 5]]
============>>>
[0 1 2 3 4 5]


In [86]:
#with np.reshape you can specify a few optional parameters

"""
a is the array to be reshaped.

newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)
"""

a = np.arange(6)  #array([0, 1, 2, 3, 4, 5])
np.reshape(a, newshape=(1, 6), order="C")

array([[0, 1, 2, 3, 4, 5]])

In [96]:
"""
How to convert 1D array into 2D array (how to add a new axis to and array)
You can use "np.newaxis" or "np.expand_dims" to increase the dimension of an existing array
"""

# np.newaxis: using newaxis will increase the dimension of an array by one dimensional when used once. This means that a 1D array become 2D array, a 2D array become 3D array, and so on.

a = np.arange(6)
print(a)
print("--------->")
a2 = a[np.newaxis, :]
print(a2)
print("---------->")
a3 = a2[np.newaxis, :]
print(a3)
print('-------------->>')
print("\ncolumn vector:")
print(a[:, np.newaxis])


[0 1 2 3 4 5]
--------->
[[0 1 2 3 4 5]]
---------->
[[[0 1 2 3 4 5]]]
-------------->>

column vector:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [97]:
# You can use np.expand_dims to add an axis at index position 1 and also index position 0:
a = np.arange(6)
print(a.shape)
print(a)
print('==========>>>')
a1 = np.expand_dims(a, axis=1)
print(a1.shape)
print(a1)
print("==========>>>")
a0 = np.expand_dims(a, axis=0)
print(a0.shape)
print(a0)

(6,)
[0 1 2 3 4 5]
==========>>>
(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
==========>>>
(1, 6)
[[0 1 2 3 4 5]]


In [100]:
"""
* Indexing and Slicing
    you can index and slice numpy arrays in the same way you can slice pytho  lists.
"""

data = np.array([1, 2, 3])
print("data:", data)
print("\ndata[1] ==>", data[1])
print("\ndata[:2] ==>", data[:2])
print("\ndata[1:] ==>:", data[1:])
print("\ndata[-2:] ==>", data[-2:])

data: [1 2 3]

data[1] ==> 2

data[:2] ==> [1 2]

data[1:] ==>: [2 3]

data[-2:] ==> [2 3]


In [105]:
"""
You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you'll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill conditions, it's straightforward with NumPy
"""

#select elements that are smaller than 7
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 7])

[1 2 3 4 5 6]


In [109]:
# select elements that are grater or equal to 8 
print(a[a >= 8])

[ 8  9 10 11 12]


In [108]:
# select elements that are divisible by 2
print(a[a%2 == 0])

[ 2  4  6  8 10 12]


In [113]:
# you can use &(and) and |(or) operators to satisfy two conditions:
c = a[(a > 2) & (a < 10)]
c

array([3, 4, 5, 6, 7, 8, 9])

In [114]:
less_or_equal_to_5 = (a < 5) | (a == 5)
less_or_equal_to_5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [116]:
# You can also use np.nonzero() to print the indices of elements that are, for example less than 5

b = np.nonzero(a < 5)
print(b)

# In this example, a tuple of arrays was returned: one for each dimensions.
# The first array represent the row indices where these values are founds, and second array represent the column indices where the values are found

print('\n\n===========>>>>')
print(np.nonzero(a%2==0))

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


===========>>>>
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([1, 3, 1, 3, 1, 3], dtype=int64))


In [121]:
"""
How to create an array from an existing array:
--> This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), .copy()
"""

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#You can create a new array from section of an existing array:
arr1 = a[3:8]
print(arr1)
print('\n=================\n')

# you can also stack two existing arrays, both vertically and horizontally
a1 = np.array([
    [1, 1],
    [2, 2]
])
a2 = np.array([
    [3, 3],
    [4, 4]
])
print(a1)
print("------------")
print(a2)
print("\nvstack:", np.vstack((a1, a2)))
print("\nhstack:", np.hstack((a1, a2)))

[4 5 6 7 8]


[[1 1]
 [2 2]]
------------
[[3 3]
 [4 4]]

vstack: [[1 1]
 [2 2]
 [3 3]
 [4 4]]

hstack: [[1 1 3 3]
 [2 2 4 4]]


In [124]:
# You can split an array into several smaller arrays using "hsplit".
# You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

x = np.arange(1, 25).reshape(2, 12)
print("x:", x)

# if you want to split this array into three equally shaped arrays, you would run:
equally_shaped = np.hsplit(x, 3)
print("\n\nEqually Shaped:", equally_shaped)

# if you want to split your array after third and fourth column:
shape_by_columns = np.hsplit(x, (3, 4))
print("Split after Third and Fourth columns:", shape_by_columns)

x: [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


Equally Shaped: [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
Split after Third and Fourth columns: [array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [126]:
"""
You can use view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it's important to be aware of this: Note: Modifying data in a view also modifies the original array!
"""

a = np.arange(1, 13).reshape(3, 4)
print("a:", a)
b1 = a[0, :]
print("\nb1:", b1)
b1[0] = 99
print("\nb1:", b1)
print("\na:", print(a))

a: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

b1: [1 2 3 4]

b1: [99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a: None


In [129]:
# Using "copy()" method will make a complete copy of the array and its data(a deep copy).
a = np.array([1, 2, 3, 4, 5])
print("a:", a)
b = a.copy()
c = a[:3]
print("\nb:", b)
print("\nc:", c)

b[0] = 88
print("\nb:", b)
print("a:", a)

a: [1 2 3 4 5]

b: [1 2 3 4 5]

c: [1 2 3]

b: [88  2  3  4  5]
a: [1 2 3 4 5]
